<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Order;

class OrderTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $orders = [
        //     [
        //         'no_order' => 'TX240101001',
        //         'name' => 'Joko Prabowo',
        //         'address' => 'Jl. Mawar No. 123, Kota ABC',
        //         'phone' => '081234567890',
        //         'unit_id' => '1',
        //         'unit' => 'Agya',
        //         'price' => 300000,
        //         'pickup_address' => 'Kantor ABC',
        //         'start_date' => '2024-01-25',
        //         'start_time' => '17:17:00',
        //         'end_date' => '2024-01-31',
        //         'end_time' => '17:17:00',
        //         'duration' => 7,
        //         'total_price' => 2100000,
        //     ],
        //     [
        //         'no_order' => 'TX240101002',
        //         'name' => 'Anita Setiawan',
        //         'address' => 'Jl. Kenanga No. 45, Kota XYZ',
        //         'phone' => '087654321098',
        //         'unit_id' => '5',
        //         'unit' => 'Land Cruiser',
        //         'price' => 500000,
        //         'pickup_address' => 'Bandara Internasional XYZ',
        //         'start_date' => '2024-02-02',
        //         'start_time' => '09:00:00',
        //         'end_date' => '2024-02-10',
        //         'end_time' => '09:00:00',
        //         'duration' => 8,
        //         'total_price' => 4000000,
        //     ],
        //     [
        //         'no_order' => 'TX240101003',
        //         'name' => 'Rina Wijaya',
        //         'address' => 'Jl. Dahlia No. 67, Kota PQR',
        //         'phone' => '089876543210',
        //         'unit_id' => '8',
        //         'unit' => 'Luxury Bus Mercy',
        //         'price' => 1500000,
        //         'pickup_address' => 'Stasiun Kereta Api ABC',
        //         'start_date' => '2024-02-15',
        //         'start_time' => '14:30:00',
        //         'end_date' => '2024-02-20',
        //         'end_time' => '14:30:00',
        //         'duration' => 5,
        //         'total_price' => 7500000,
        //     ],
        //     [
        //         'no_order' => 'TX240101004',
        //         'name' => 'Surya Pratama',
        //         'address' => 'Jl. Anggrek No. 34, Kota LMN',
        //         'phone' => '081567890123',
        //         'unit_id' => '12',
        //         'unit' => 'Beat',
        //         'price' => 100000,
        //         'pickup_address' => 'Hotel XYZ',
        //         'start_date' => '2024-03-01',
        //         'start_time' => '11:00:00',
        //         'end_date' => '2024-03-07',
        //         'end_time' => '11:00:00',
        //         'duration' => 6,
        //         'total_price' => 600000,
        //     ],
        //     [
        //         'no_order' => 'TX240101005',
        //         'name' => 'Dina Marwah',
        //         'address' => 'Jl. Cempaka No. 21, Kota UVW',
        //         'phone' => '082345678901',
        //         'unit_id' => '14',
        //         'unit' => 'Supra X',
        //         'price' => 100000,
        //         'pickup_address' => 'Mall ABC',
        //         'start_date' => '2024-03-12',
        //         'start_time' => '08:45:00',
        //         'end_date' => '2024-03-20',
        //         'end_time' => '08:45:00',
        //         'duration' => 8,
        //         'total_price' => 800000,
        //     ],
        //     [
        //         'no_order' => 'TX240102001',
        //         'name' => 'Joko Prabowo',
        //         'address' => 'Jl. Mawar No. 123, Kota ABC',
        //         'phone' => '081234567890',
        //         'unit_id' => '1',
        //         'unit' => 'Agya',
        //         'price' => 300000,
        //         'pickup_address' => 'Kantor ABC',
        //         'start_date' => '2024-01-25',
        //         'start_time' => '17:17:00',
        //         'end_date' => '2024-01-31',
        //         'end_time' => '17:17:00',
        //         'duration' => 7,
        //         'total_price' => 2100000,
        //     ],
        //     [
        //         'no_order' => 'TX240102002',
        //         'name' => 'Anita Setiawan',
        //         'address' => 'Jl. Kenanga No. 45, Kota XYZ',
        //         'phone' => '087654321098',
        //         'unit_id' => '5',
        //         'unit' => 'Land Cruiser',
        //         'price' => 500000,
        //         'pickup_address' => 'Bandara Internasional XYZ',
        //         'start_date' => '2024-02-02',
        //         'start_time' => '09:00:00',
        //         'end_date' => '2024-02-10',
        //         'end_time' => '09:00:00',
        //         'duration' => 8,
        //         'total_price' => 4000000,
        //     ],
        //     [
        //         'no_order' => 'TX240102003',
        //         'name' => 'Rina Wijaya',
        //         'address' => 'Jl. Dahlia No. 67, Kota PQR',
        //         'phone' => '089876543210',
        //         'unit_id' => '8',
        //         'unit' => 'Luxury Bus Mercy',
        //         'price' => 1500000,
        //         'pickup_address' => 'Stasiun Kereta Api ABC',
        //         'start_date' => '2024-02-15',
        //         'start_time' => '14:30:00',
        //         'end_date' => '2024-02-20',
        //         'end_time' => '14:30:00',
        //         'duration' => 5,
        //         'total_price' => 7500000,
        //     ],
        //     [
        //         'no_order' => 'TX240102004',
        //         'name' => 'Surya Pratama',
        //         'address' => 'Jl. Anggrek No. 34, Kota LMN',
        //         'phone' => '081567890123',
        //         'unit_id' => '12',
        //         'unit' => 'Beat',
        //         'price' => 100000,
        //         'pickup_address' => 'Hotel XYZ',
        //         'start_date' => '2024-03-01',
        //         'start_time' => '11:00:00',
        //         'end_date' => '2024-03-07',
        //         'end_time' => '11:00:00',
        //         'duration' => 6,
        //         'total_price' => 600000,
        //     ],
        //     [
        //         'no_order' => 'TX240102005',
        //         'name' => 'Dina Marwah',
        //         'address' => 'Jl. Cempaka No. 21, Kota UVW',
        //         'phone' => '082345678901',
        //         'unit_id' => '14',
        //         'unit' => 'Supra X',
        //         'price' => 100000,
        //         'pickup_address' => 'Mall ABC',
        //         'start_date' => '2024-03-12',
        //         'start_time' => '08:45:00',
        //         'end_date' => '2024-03-20',
        //         'end_time' => '08:45:00',
        //         'duration' => 8,
        //         'total_price' => 800000,
        //     ],
        //     [
        //         'no_order' => 'TX240103001',
        //         'name' => 'Joko Prabowo',
        //         'address' => 'Jl. Mawar No. 123, Kota ABC',
        //         'phone' => '081234567890',
        //         'unit_id' => '1',
        //         'unit' => 'Agya',
        //         'price' => 300000,
        //         'pickup_address' => 'Kantor ABC',
        //         'start_date' => '2024-01-25',
        //         'start_time' => '17:17:00',
        //         'end_date' => '2024-01-31',
        //         'end_time' => '17:17:00',
        //         'duration' => 7,
        //         'total_price' => 2100000,
        //     ],
        //     [
        //         'no_order' => 'TX240103002',
        //         'name' => 'Anita Setiawan',
        //         'address' => 'Jl. Kenanga No. 45, Kota XYZ',
        //         'phone' => '087654321098',
        //         'unit_id' => '5',
        //         'unit' => 'Land Cruiser',
        //         'price' => 500000,
        //         'pickup_address' => 'Bandara Internasional XYZ',
        //         'start_date' => '2024-02-02',
        //         'start_time' => '09:00:00',
        //         'end_date' => '2024-02-10',
        //         'end_time' => '09:00:00',
        //         'duration' => 8,
        //         'total_price' => 4000000,
        //     ],
        //     [
        //         'no_order' => 'TX240103003',
        //         'name' => 'Rina Wijaya',
        //         'address' => 'Jl. Dahlia No. 67, Kota PQR',
        //         'phone' => '089876543210',
        //         'unit_id' => '8',
        //         'unit' => 'Luxury Bus Mercy',
        //         'price' => 1500000,
        //         'pickup_address' => 'Stasiun Kereta Api ABC',
        //         'start_date' => '2024-02-15',
        //         'start_time' => '14:30:00',
        //         'end_date' => '2024-02-20',
        //         'end_time' => '14:30:00',
        //         'duration' => 5,
        //         'total_price' => 7500000,
        //     ],
        //     [
        //         'no_order' => 'TX240103004',
        //         'name' => 'Surya Pratama',
        //         'address' => 'Jl. Anggrek No. 34, Kota LMN',
        //         'phone' => '081567890123',
        //         'unit_id' => '12',
        //         'unit' => 'Beat',
        //         'price' => 100000,
        //         'pickup_address' => 'Hotel XYZ',
        //         'start_date' => '2024-03-01',
        //         'start_time' => '11:00:00',
        //         'end_date' => '2024-03-07',
        //         'end_time' => '11:00:00',
        //         'duration' => 6,
        //         'total_price' => 600000,
        //     ],
        //     [
        //         'no_order' => 'TX240103005',
        //         'name' => 'Dina Marwah',
        //         'address' => 'Jl. Cempaka No. 21, Kota UVW',
        //         'phone' => '082345678901',
        //         'unit_id' => '14',
        //         'unit' => 'Supra X',
        //         'price' => 100000,
        //         'pickup_address' => 'Mall ABC',
        //         'start_date' => '2024-03-12',
        //         'start_time' => '08:45:00',
        //         'end_date' => '2024-03-20',
        //         'end_time' => '08:45:00',
        //         'duration' => 8,
        //         'total_price' => 800000,
        //     ],
        // ];

        // Order::insert($orders);
    }
}
