export const tourPackages = [
    {
        image: "/images/paket-wisata/wisata1.jpg",
        title: "Paket Cahaya 1 (GOLD) Rp1.590.000 / pax",
        destinations: [
            { day: 1, place: "Rafting Elo" },
            { day: "-", place: "Candi Borobudur" },
            { day: "-", place: "Pawon Luwak" },
            { day: 2, place: "Keraton Yogyakarta" },
            { day: "-", place: "Malioboro" },
            { day: "-", place: "Beringharjo" },
        ],
        includes: [
            "Transport",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata2.jpg",
        title: "-Paket Cahaya 2 (EKSEKUTF) Rp1.440.000 / pax",
        destinations: [
            { day: 1, place: "Hutan Pinus" },
            { day: "-", place: "Gua Pindul" },
            { day: "-", place: "Pantai Indrayanti" },
            { day: 2, place: "Keraton Yogyakarta" },
            { day: "-", place: "Malioboro" },
            { day: "-", place: "Pasar Beringharjo" },
        ],
        includes: [
            "Transport",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata3.jpg",
        title: "Paket Cahaya 3 (HEMAT) Rp.900.000/PAX",
        destinations: [
            { day: 1, place: "Hutan Pinus" },
            { day: "-", place: "Gua Pindul" },
            { day: "-", place: "Pantai Indrayanti" },
            { day: 2, place: "Keraton Yogyakarta" },
            { day: "-", place: "Malioboro" },
            { day: "-", place: "Pasar Beringharjo" },
        ],
        includes: [
            "Transport",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata4.jpg",
        title: "Paket CW 1  Rp. 1.300.000/Pax",
        destinations: [
            { day: 1, place: "Keraton Jogja" },
            { day: "-", place: "Taman Sari" },
            { day: "-", place: "Candi Borobudur" },
            { day: 2, place: "Hutan Pinus" },
            { day: "-", place: "Goa Pindul" },
            { day: "-", place: "Pantai Indrayanti" },
            { day: 3, place: "Batik Winotosastro" },
            { day: "-", place: "alan Malioboro" },
            { day: "-", place: " pasar Beringharjo" },
        ],
        includes: [
            "Transport",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata5.jpg",
        title: "Paket CW 3 (Gold) HARGA Rp. 2.240.000",
        destinations: [
            { day: 1, place: "Rafting Elo" },
            { day: "-", place: " Candi Borobudur" },
            { day: "-", place: "Pawon Luwak" },
            { day: 2, place: "Hutan Pinus" },
            { day: "-", place: "Goa Pindul" },
            { day: "-", place: "Pantai Indrayanti" },
            { day: 3, place: "Keraton Yogyakarta" },
            { day: "-", place: "alan Malioboro" },
            { day: "-", place: " pasar Beringharjo" },
        ],
        includes: [
            "Transport",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata6.jpg",
        title: "Paket CW 3 (EKSEKUTF) HARGA 2.050.000",
        destinations: [
            { day: 1, place: "Keraton Yogyakarta" },
            { day: "-", place: "Taman Sari" },
            { day: "-", place: "Candi Borobudur" },
            { day: 2, place: "Hutan Pinus" },
            { day: "-", place: "Goa Pindul" },
            { day: "-", place: "Pantai Indrayanti" },
            { day: 3, place: "Batik Winotosastro" },
            { day: "-", place: "jalan Malioboro" },
            { day: "-", place: " pasar Beringharjo" },
        ],
        includes: [
            "Transport",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata7.jpg",
        title: "PAKET WASKITA HEMAT Harga 1.590.000/pax",
        destinations: [
            { day: 1, place: "Keraton Yogyakarta" },
            { day: "-", place: "Taman Sari" },
            { day: "-", place: "Candi Borobudur" },
            { day: 2, place: "Merapi Lava Tour" },
            { day: "-", place: "Tebing Breksi" },
            { day: "-", place: "Ratu Boko" },
            { day: 3, place: "Hutan Pinus" },
            { day: "-", place: "Gua Pindul" },
            { day: "-", place: " Pantai Indrayanti" },
            { day: 4, place: " Batik Winotosastro" },
            { day: "-", place: " Jalan Malioboro" },
            { day: "-", place: "Beringharjo" },
        ],
        includes: [
            "Transport",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata8.jpg",
        title: "Paket waskitha Eksekutf (CUKUPAN) HARGA 2.650.000",
        destinations: [
            { day: 1, place: "Keraton Yogyakarta" },
            { day: "-", place: "Taman Sari" },
            { day: "-", place: "Candi Borobudur" },
            { day: 2, place: "Merapi Lava Tour" },
            { day: "-", place: "Tebing Breksi" },
            { day: "-", place: "Ratu Boko" },
            { day: 3, place: "Hutan Pinus" },
            { day: "-", place: "Gua Pindul" },
            { day: "-", place: " Pantai Indrayanti" },
            { day: 4, place: " Batik Winotosastro" },
            { day: "-", place: " Jalan Malioboro" },
            { day: "-", place: " Pasar Beringharjo" },
        ],
        includes: [
            "Transport",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata9.jpg",
        title: "Paket waskitha Eksekutf (CUKUPAN) HARGA 2.650.000",
        destinations: [
            { day: 1, place: "Lava Tour Merapi" },
            { day: "-", place: "Tebing Brexi" },
            { day: "-", place: "Kraton Ratu Boko" },
            { day: 2, place: "Rafting Elo" },
            { day: "-", place: "Candi Borobudur" },
            { day: "-", place: "RPawon Luwak" },
            { day: 3, place: "Hutan Pinus" },
            { day: "-", place: "Gua Pindul" },
            { day: "-", place: " Pantai Indrayanti" },
            { day: 4, place: " Keraton Ngayogyakarta" },
            { day: "-", place: "Malioboro" },
            { day: "-", place: "Beringharjo" },
        ],
        includes: [
            "Transport",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
];
