export const tourPackages = [
    {
        image: "/images/paket-wisata/wisata1.jpg",
        title: "Paket 1 Hari (One Day Tour) Jogja",
        destination: "Jogja",
        prices: [
            { pax: 2, price: 580000 },
            { pax: 3, price: 520000 },
            { pax: 4, price: 485000 },
            { pax: 5, price: 420000 },
            { pax: "6-8", price: 395000 },
            { pax: "9-12", price: 390000 },
        ],
        includes: [
            "Transport",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata2.jpg",
        title: "Paket 2 Hari 1 Malam Jogja",
        destination: "Jogja",
        prices: [
            { pax: "4-5", price: 970000 },
            { pax: "6-15", price: 940000 },
            { pax: "16-25", price: 920000 },
            { pax: "26-35", price: 905000 },
            { pax: "36-45", price: 885000 },
            { pax: "46-55", price: 865000 },
        ],
        includes: [
            "Transport",
            "Hotel",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata3.jpg",
        title: "Paket 3 Hari 2 Malam Jogja",
        destination: "Jogja",
        prices: [
            { pax: "4-5", price: 1545000 },
            { pax: "6-15", price: 1525000 },
            { pax: "16-25", price: 1505000 },
            { pax: "26-35", price: 1490000 },
            { pax: "36-45", price: 1470000 },
            { pax: "46-55", price: 1450000 },
        ],
        includes: [
            "Transport",
            "Hotel",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata4.jpg",
        title: "Paket Outbound Jogja",
        destination: "Jogja",
        lists: [
            "Gold",
            "Executive",
            "Hemat",
            "1 Hari Outbound",
            "2 Hari 1 Malam",
            "3 Hari 2 Malam",
        ],
        includes: [
            "Transport",
            "Hotel",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata5.jpg",
        title: "Paket Honeymoon Jogja",
        destination: "Jogja",
        lists: [
            "Premium",
            "Deluxe",
            "Standart",
            "Private Pool",
            "3 Hari 2 Malam",
            "2 Hari 1 Malam",
        ],

        includes: [
            "Transport",
            "Hotel",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata6.jpg",
        title: "Paket Study Tour Jogja",
        destination: "Jogja",
        prices: [
            { pax: "25-30", price: 1225000 },
            { pax: "31-35", price: 1175000 },
            { pax: "36-40", price: 1125000 },
            { pax: "41-45", price: 1100000 },
            { pax: "46-50", price: 1070000 },
            { pax: "51-55", price: 1000000 },
        ],
        includes: [
            "Transport",
            "Hotel",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata7.jpg",
        title: "Paket Tour Dieng 2 Hari 1 Malam (2H1M)",
        destination: "Dieng",
        prices: [
            { pax: "4-5", price: 1125000 },
            { pax: "6-15", price: 1045000 },
            { pax: "16-25", price: 990000 },
            { pax: "26-35", price: 935000 },
            { pax: "36-45", price: 895000 },
            { pax: "46-55", price: 875000 },
        ],
        includes: [
            "Transport",
            "Hotel",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata8.jpg",
        title: "Paket Tour Bali 2 Hari 1 Malam (2H1M)",
        destination: "Bali",
        prices: [
            { pax: "4-5", price: 1520000 },
            { pax: "6-15", price: 1450000 },
            { pax: "16-25", price: 1390000 },
            { pax: "26-35", price: 1320000 },
            { pax: "36-45", price: 1290000 },
            { pax: "46-55", price: 1270000 },
        ],
        includes: [
            "Transport",
            "Hotel",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
    {
        image: "/images/paket-wisata/wisata1.jpg",
        title: "Corporate Gathering",
        lists: [
            "OPSIONAL:",
            "2H-1M",
            "3H-2M",
            "4H-3M",
            "Gala Dinner + Entertain",
            "Tanpa Gala Dinner",
        ],
        includes: [
            "Transport",
            "Hotel",
            "Guide (Group)",
            "BBM",
            "Air Mineral",
            "Makan",
            "Parkir",
            "Jeep Merapi",
            "Tipping",
        ],
    },
];
